### PR TITLE
Knockout.js 1.3 RC

### PR DESCRIPTION
**Pull request by andrewharry**

### CODE REVIEW

**Comment by nikhilk** [comment]
Note, I made some changes after merging the change.
- Some were about styling related things including K&R style bracing and member ordering.
- I think I know what happened regarding more lines showing up as different - had to do with line endings. Do you have your autocrlf git config property set to true?
- Also adjusted modifiers of Subscribable and Observable to prevent creation/derivation outside of the Knockout assembly.

Can you double check everything still works...

**Comment by andrewharry** [comment]
As long as we can still create a new instance of a subscribable via the knockout class it should be all good.
This represents my first explicit contribution to open source software :)

I will pull your changes and make sure it is all working correctly tonight.

Cheers!

**Comment by nikhilk** [comment]
Thanks for contributing!
Just heads up (hopefully there won't be an issue) but I won't be able to make any changes next couple weeks, so if there is an issue, please do update in your fork of the project.

**Comment by andrewharry** [comment]
Sounds like you are having a holiday :)  If so - enjoy!

**Pull request merged**
