### PR TITLE
Created stubs for global timers in NodeJS

### PR DESCRIPTION
**Pull request by theoutlander**
Ignore the logging library as I had reverted it after our conversation. I don't know how to remove it from my repo entirely.

### CODE REVIEW

**Comment by nikhilk** [comment]
You should be able to use the APIs on the Script class for Clear/SetTimeout etc. Those are globals that exist across different script environments (nodejs and browser), and hence they've been moved there (from Window, which is where they used to be).

**Comment by nikhilk** [comment]
On your question of reverting changes, I believe a git squash will allow you to remove previous commits.

I've been learning git as I go along as well, and I think the flow that has each feature done in its own branch also better allows for merging all changes into a single change before it is merged back into the parent branch.

**Comment by theoutlander** [comment]
Oh, didn't think of using the Script class....searched in the Node project and didn't see those methods. The confusion in using Script is that not everything from there is applicable to Node. Wouldn't it be intuitive to have Node's globals in the Node class?

**Comment by nikhilk** [comment]
Everything in the Script class should apply to all scripting environments. Did you find something that didn't work in node?

The reason I put something like SetTimeout in script rather than duplicate in both Window for browser and Node for nodejs, is you might very well write some code that could/needs to run in both environments.

**Comment by theoutlander** [comment]
Good point about running code across environments. I'll have to check (later) on the specific functions that don't work. I looked at what Script exposed and compared it to what [Node Globals](http://nodejs.org/api/globals.html) listed and also tried out a couple of them in the Node console and they failed to work. From the top of my head, I think a couple of them were GetField, DeleteField....simply looking at the nodejs api in a single page and searching for those methods doesn't show them either.

As an alternative, do we have the ability to decorate methods as applicable to specific environments? That might be useful in browser-specific API's as well (which I'm not really a big fan of).

**Comment by nikhilk** [comment]
Script.GetField, SetField etc. get rewritten by the compiler to the appropriate script syntax.

Long ago, I also had the idea of marking environment-specific APIs (eg. an IE-only API etc.) and then having FxCop rules that you could turn on that would flag things. The reason FxCop and not compilation ... because you might very well be writing an environment-specific script (eg. something that wraps an IE only API) and want to suppress message rather than get compiler warnings or errors.

**Comment by theoutlander** [comment]
Aah, I suspected it was doing something else and wanted to try in the compiler. As long as all the methods are compatible with Node, it makes sense. I guess I'll retract this request to pull. I'll try GIT squash on it ;).

**Pull request closed without merging**
