### PR TITLE
Added support for StyleSheets API

### PR DESCRIPTION
**Pull request by viceroypenguin**
Based on API documentation here: http://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/css.html

document.styleSheets is accessible in all modern browsers, and is a useful way to directly change the effect of a rule on all elements satisfying that css rule.

### CODE REVIEW

**Comment by nikhilk** [comment]
Its great to see contributions start happening, like this one. Thanks.

I'd like to suggest a few changes and a few comments that I think will help at the API level, and at the code level:
- Change the namespace to match the HTML5 spec area, i.e. CSS -> StyleSheets.
- CSS prefix to Style prefix (eg. CSSRule to StyleRule) ... easier to read than the sequence of uppercase characters. Also probably should apply it consistently ... eg. MediaList should probably be StyleMediaList.
- Change the consts defined on CSSRule to instead be an enum decorated with [ScriptConstants] ... this gets you named constants in c# code that are strongly typed, and translates to numeric values at runtime.

Everything else looks great.

And one last one - could you change to tabs (defined to expand to 4 spaces) ... I can't tell on github if its a tab or just 2 spaces indent. Either way, the rest of the code uses 4 spaces as indentation. But thanks for following other aspects of the coding guidelines.

**Comment by viceroypenguin** [comment]
The CSS Prefix had me curious as well, because I can argue for CSS, Style, or dropping prefix altogether.  Being an architect I understand the importance of naming (and styling) so I attempting to follow your general guidelines as much as I could.  Your way sounds better on the prefix, so I'll take care of that today.  

I use tabs everywhere, so I wasn't paying that much attention to the spaces/tabs thing.  I'll switch that over today as well.

I wasn't sure how you wanted the constants done, but that makes sense.  

Thanks!

**Comment by viceroypenguin** [comment]
One further question: I would like to do either `jQuery.Grep(Document.StyleSheets)` or `foreach(StyleSheet ss in Document.StyleSheets)`. What would be the best way to annotate StyleSheetList to accommodate one of these enumeration patterns (or both)?

**Comment by nikhilk** [comment]
jQuery.Grep - maybe we should add an implicit conversion operator to Array and that will allow passing in a StyleSheetList to jQuery.Grep.

Foreach should work if we just explicitly implement IEnumerable on StyleSheetList. At runtime, it will look if the object has a getEnumerator method, and it won't, so it will fall back on length + indexed access. It would be interesting to see if the implicit conversion operator to Array would do by itself, i.e. since Array is already enumerable.

**Comment by viceroypenguin** [comment]
Thanks - this should be good to go now.  Let me know if you have any more concerns or comments on it.

**Comment by nikhilk** [comment]
Thanks for the contrib - will be making couple of changes ...
- Making IEnumerable implementations explicit, so intellisense doesn't show a GetEnumerator method.
- Making StyleRule ctor internal, as it doesn't make sense to derive outside the assembly.
- Removing the consts now that we have a rule type enum.

**Pull request merged**
