### PR TITLE
Initial adaptation of jQuery.Globalize

### PR DESCRIPTION
**Pull request by viceroypenguin**
Only implements the format and parse\* methods.  I'll come back this week or next and render the rest of the Globalize methods.

### CODE REVIEW

**Comment by nikhilk** [comment]
How useful is jQuery.Globalize relative to what script# offers in ss.js? Hopefully what ss.js provides will feel more natural to c# developers (CultureInfo APIs, String.Format-based format specifiers etc.)

What is the delta that isn't catered by script#? Would be useful to know, to consider filling that gap.

One thing we do need to do is write a tool to generate the locale specific addendum to ss.js to provide specific culture data for CultureInfo.CurrentCulture (right now CultureInfo.CurrentCulture == CultureInfo.InvariantCulture). This should be straight-forward ... just need to figure out how locale-specific scripts plug into an AMD-style loading pattern.

**Comment by viceroypenguin** [comment]
Hmm... good question.  I first started using Script# back in the v0.5 days and have other parts of the application that don't use Script# at all, so I created the Globalize library on my own to match with the available js project.  All I did here was update my library to v0.8 code and import it.

Since Script# has globalization code, the Globalize library may not be necessary for the Script# project.  If so, I'll just keep my copy private.

This may or may not be a valid point (not having looked at the Script# globalization code), but I do have KO bindings that are set up as `data-bind="text: Globalize.format(value(), 'n2')"`.  Does Script# have an easily accessible function to call from raw JS to do similar? I ask because I don't like the thought of changing the KO binding to have complicated code - the point of KO being easy declaration of bindings.

**Comment by nikhilk** [comment]
The equivalent call would be something like:

```
ss.format('{0:n}', value())
```

This is what String.Format in your own code maps to. A culture (eg. ss.culture.neutral or ss.culture.current) can be passed in into ss.format as well that affects number and date formatting.

If you're using an AMD loader in your page however, the script# runtime doesn't add globals (unlike jQuery which adds jQuery, and from your example, looks like Globalize adds yet more, rather than being underneath jQuery). So to use in that manner, you'd need to assign the ss object from within your assembly or within a requires script at the page level to the window object.

**Comment by viceroypenguin** [comment]
Then I'm good with ignoring the Globalize library.  We're not all the way up to v0.8 in our internal applications yet, but I've been working on getting code ready so the transition will be smoother.  I'll keep this info bookmarked as part of the migration project.

**Comment by michaelaird** [comment]
I'd made a local build of jQuery Globalize imports as well. If i recall correctly, the big selling feature was being able to do ParseDate with multiple acceptable formats and also being able to call ParseFloat for locales that use the "," as the decimal separator.

**Comment by nikhilk** [comment]
Yes, you're right. Parsing is all routed to intrinsic script APIs, so doesn't account for globalization. Would certainly be worthwhile trying to get custom globalized parseInt/Float/Date into ss.js, since the formatting half is already there.

**Comment by viceroypenguin** [comment]
For what it's worth, I think it would be useful to defer to jQuery.Globalize for the heavy lifting on parsing, formatting, and culture management.  They have an existing library set up to handle all of the .NET cultures.  We could explain that the built-in formatting only supports "en-US" and should you desire to incorporate multiple cultures, you would need to include jQuery.Globalize.  

I think (theoretically) the loading scripts could be set up to allow the format/parse functions to recognize jQuery.Globalize has been loaded and defer as necessary, but use internal functions if it hasn't.  This would allow Script# to not have an explicit dependency, but keep the code the same for either case.  I believe that jQuery.Globalize itself doesn't have any dependencies on jQuery proper, it's only included as part of the jQuery projects so jQuery can take ownership of it.

If that isn't a valid idea, I think the Generator code could easily be pulled from the jQuery.Globalize project and used to generate cultures.

Either way, I think that including multiple cultures should be done as a separate file and explicitly included as desired.  Should I have time in the near future, I think I might be interested in writing the code to recognize jQuery.Globalize and use it as a backend to Script# parse/format functions.  I'd need to know a little bit more about the existing parse/format architecture (if it's not readily available from the code - I haven't looked that closely yet).

**Pull request closed without merging**
