### PR TITLE
New .toggle() signature for the EffectObject

### PR DESCRIPTION
**Pull request by StebQC**
I used the signature from the jquery-ui API documentation

### CODE REVIEW

**Comment by nikhilk** [comment]
It would be interesting to see if this can be accounted into the generator that was used to generate the jQueryUI assembly (see https://github.com/igochkov/ScriptSharpJQueryUI). Could you take a quick look?

Also, rather than a string effect, should this be using an enum value (similar to how string constants are modeled in the rest of the API)?

**Comment by StebQC** [comment]
Hi Nikhil,

The generator ScriptSharpJQueryUI create a folder named "Methods" for all
the methods overriden in jQueryUI from jQuery (see
http://api.jqueryui.com/category/overrides/). Those methods are not
generated properly in the sense that the signatures are wrong. Do you think
it would be a good idea to adapt the generator? Also, as these function are
called on standard jquery object, I was thinking of linking these methods
on .Plugin<jQueryUIObject>(). What do you think ?

For your other question, yes, I think it would be better to use a enum to
represent the effect.

Cheers,
Sebastien

**Comment by nikhilk** [comment]
We should definitely try and update the generator. The generator project also had support for 1.9 started, which would be interesting to bring forth, now that jQueryUI has updated.

As for method overrides, yes, would be good to get the overridden signatures into jQueryUIObject.

**Comment by StebQC** [comment]
I've updated the generator project and ran it against the jqueryui 1.9 documentation. There is a lot a changes that would impact the scriptsharp project. Would you think it would be better to split the library (jqueryui in scriptsharp) for version 1.8 and 1.9 or just stay up to date with the jqueryui version ?

**Comment by nikhilk** [comment]
From email conversation with the owner of the generator project, my understanding is the latest docs need to be incorporated into the project and changes made to the generator to accomodate them. I noticed you have a fork of that project... so did you by any chance pick up those new docs?

As far as incorporating the updated assembly back into script#, as long as 1.9 is backward compatible with 1.8, I'd rather just have a single import assembly for jQueryUI, rather than start having to manage version-specific assemblies.

**Comment by StebQC** [comment]
Sorry for not getting back to you earlier, I was busy with other projects.

I have incorporated the latest docs into the project. I modified some code
in the generator to incorporate the _Include_ Xml schema as they use it
quite heavily in the latest docs. As far as I understand, the generated doc
must be modified by the user before being incorporated into scriptsharp
project. Do you know if it was the case in version 1.8 ?

Thanks,
Sebastien

**Comment by nikhilk** [comment]
No problem. Can you check with @igochkov since he started the project, and might also be looking into updating for 1.9... and hopefully that will save some effort.

**Pull request closed without merging**
