### PR TITLE
Added support for Node-Neo4J Graph Database Client Library

### PR DESCRIPTION
**Pull request by theoutlander**

### CODE REVIEW

**Comment by theoutlander** [comment]
One thing I have pondered over is if the entity names should have the Neo4J prefix. I followed the convention from looking at the other Node projects.

Also, notice that I've removed the IgnoreNamespace attribute on the Neo4JGraph class. The reason is that once the library is imported, it is assigned to a variable called Neo4J. The only want to create an instance of the graph object is by calling Neo4J.Graph. This might not be the right way to do it, so let me know if there's a better way to do it.

**Comment by nikhilk** [comment]
I really don't have any experience with this neo4j APIs, but that said:
- I think "Neo4J" as a namespace is fine, but perhaps class names should not have "Neo4J" in them. Instead GraphNode, GraphPath etc. would be much nicer. Yep, that is inconsistent with Express and Mongo examples. Maybe just "Neo" and while that is just odd as well, I wonder if its the "4" thats making it look odd. Its enough to make me question the use of "Express" and "Mongo" prefixes in those APIs. While "Mongo" could be dropped in favor of standard db terminology, not sure what would replace "Express". Maybe Express should be the exception.
- Callbacks should use AsyncCallback defined in the core node assembly. That will produce standard delegate signature of first parameter being an error, and second parameter being the result you care about.
- I think the use of IgnoreNamespace is fine. The c# namespace should be ignored. And instead the ModuleName.TypeName should be used, where module name is the name specified with ScriptAssembly. I think ScriptAssembly should have name = "neo4j" rather than "Neo4J" as you have it, so generated code looks like sample code on their github page.
- Neo4JPropertyContainer should have an internal ctor.

Is there a public hosted Neo4J service that allows you to play with a graph service? Similar to MongoLabs for mongo? It would be interesting to use it to create an example.

Out of curiosity, what are you building that relies on graphs. I ask not so much in context of script#, but in capacity of being an architect in Windows Azure (I've been pondering about some graph scenarios, and would love to learn more).

**Comment by nikhilk** [comment]
One other thing - if we do use the Neo4J prefix, it should really be Neo4j (lowercase j) to follow their branding.

Maybe Neo4jGraph doesn't look as bad. The pascal-casing works better that way as it doesn't look like "Neo4" + "JGraph" ... yes, I'll admit, I think way more about API naming than I should. Its a left-over trait from the days of designing .net framework APIs. Sometimes its a useful trait. :)

**Comment by theoutlander** [comment]
- I agree that API naming can get you thinking more than others especially since you were part of the API team. I like both the naming conventions that you've suggested, but the Graph prefix seems closer to the structure and since the namespace already makes it clear which system we're working with I think I'll change everything to Graph*.
- Changing Action to AsyncCallback
- Changed Neo4J to neo4j. Added IgnoreNamespace back to GraphDatabase class. Changed ScriptName attribute value to "neo4j.GraphDatabase" - is that what you wanted me to do?
- Added internal constructor to PropertyContainer. Although, I'm wondering why that's needed with an abstract class?
- There isn't a publicly hosted Neo4J instance that I know of. However, it is very easy to set it up as it simply entails unzipping the package and executing the batch file assuming JVM is installed. Another alternative is to run the neo4j add-on on Heroku @ https://addons.heroku.com/neo4j. That's basically running a free micro-instance of EC2 indefinitely. Probably not the solution you're looking for.
- I can tell you more about my graph usage in-person this weekend (are we still on?)
- On a side note, I have some questions related to Azure HPC involving large data-sets (unrelated to the graph)

**Comment by nikhilk** [comment]
I have to try this... I believe we can just remove ScriptIgnoreNamespace and have module name be picked up from the ScriptAssembly attribute, rather than creating a script name with module name inside it. I'd like to have the namespace/file paths match the Neo4j name casing. I can take care of these once I merge as it might require a bit of playing around.

The reason for internal ctor to PropertyContainer is so someone cannot extend from it outside of the assembly, as that isn't a true class at runtime that can be extended from with the script# class pattern (likely) and probably won't make sense either.

Will send mail to set something up...

**Comment by theoutlander** [comment]
Sorry for the confusion. I know it works when I remove ScriptIgnoreNamespace. but I thought you wanted it back in place (we lose the ability to output Module.Typename at that point, so I did the workaround).

Doh! I see your point with PropertyContainer. I was just exhausted and not thinking.

**Comment by theoutlander** [comment]
Check this out https://github.com/Readify/Neo4j.Server.AzureWorkerHost

**Pull request merged**
