### PR TITLE
Introduce QuerySelector and Trim Parameters

### PR DESCRIPTION
**Pull request by andekande**
Query Selector for XmlNode because SelectSingleNode is only available in IE
Trim with Paramaters to behave more like in .Net and also fixed compatibility to IE8

Sorry for the messy History, couldn't quickly figure out how to branch after work was done

### CODE REVIEW

**Comment by nikhilk** [comment]
I wonder if we should instead have Trim APIs take in a string trimCharacters parameter instead of a params char[] trimChars, as that would simplify the script implementation. Every little bit counts in keeping ss.js small.

**Comment by andekande** [comment]
Reason why it is not a string in .Net is to avoid misconception about the order of letters you put in it. Any letter in any order gets trimmed. So maybe a better Parameter is a simple new char[] { 'H', 'e', 'l', 'l', 'o' }

**Comment by nikhilk** [comment]
I'd argue the string version wouldn't be that unclear... but willing to go  with the non-params array approach, so its still similar to .net.

I can take care of making the changes if you want. To address the history issue, you'll likely need to do a "git rebase -i master" to squash individual commits you don't want to see.

**Comment by nikhilk** [comment]
Took care of this. Per the note above added support without params capability, which makes for smaller runtime script. Also added relevant test cases.

On XML APIs, I also removed the older IE-only APIs.

**Pull request closed without merging**
