### PR TITLE
Added missing Validator options

### PR DESCRIPTION
**Pull request by stevehobbsdev**
.. for:
- Highlight
- Unhighlight
- IgnoreTitle

### CODE REVIEW

**Comment by nikhilk** [comment]
Getting merge errors with this... maybe it has to do with the commit history accumulated with this. I am sure there must be a mechanism to clean up the history.

Also, I am trying to keep all current development going into the next build in the "cc" branch, so rather repeated handling of merge conflicts each step of the way, perhaps I'll go ahead and incorporate the changes manually into that branch. I'd also like to rename HighlightElementCallback to jQueryHighlightCallback to be in sync with other types in this assembly.

Thoughts on both?

**Comment by stevehobbsdev** [comment]
The rename is fine, of course.

Should we be submitting pull requests into cc then? Or is this something you will handle yourself?

**Comment by nikhilk** [comment]
I'll handle this right now... realize most folks are based on released bits, and so changes will go in master... but meanwhile I am in a state where I really need to get 0.8 done, so trying to get everything there.

**Comment by nikhilk** [comment]
Added your updates... hopefully it doesn't result in too many merge conflicts on your end instead...

**Pull request closed without merging**
