### PR TITLE
TestCase for base method Calls, see Issue #295

### PR DESCRIPTION
**Pull request by andekande**
Always when you call a base method (other than that you are overwriting) in an overridden method, inheritance crashes.
Does not happen, if the other base method you are calling did itself got overridden in the same class, even when calling its own base. (workaround)

BTW: edited Chrome start because Registry Key did not exist (Win7, 64bit, Chrome 25)

### CODE REVIEW

**Comment by nikhilk** [comment]
Question - I only see test changes. What was the fix?

**Comment by andekande** [comment]
I have no idea how to fix it, that's why at least I wanted to show when exactly inheritance breaks.
All I know is, that the code gooing into Loop is in TypeSystem.js in line 156: function base(instanceOrType, method)

**Comment by nikhilk** [comment]
#295 was fixed and closed... per the fix suggested in the issue. Looking at that, it seems another scenario/issue was added after it was closed, and so I think I never got to see it. I'd suggest opening a new bug rather than add to a closed issue.

I also noticed you had a repro included in the issue, which is a much better way to go about it than creating a pull request that leaves tests in a broken state.

**Comment by nikhilk** [comment]
I'd suggest re-opening this or opening a new issue with an isolated repro listed in the issue, rather than changing a test to include something that breaks.

Its unclear from the multiple changes you made what is broken, what works, and what is a workaround. Also, when creating a repro, you don't need to pick the scenario that is in the test case but rather use some more straightforward scenario to illustrate.

Thanks

**Pull request closed without merging**
