### PR TITLE
Added BindingContext to BindingHandler method signatures

### PR DESCRIPTION
**Pull request by michaelaird**
Updated the method signature to include the binding context. this is key for calling other bindinghandlers because you need to pass the context in or it gets nulled.

Also, I don't love the name "UntypedBindingContext" so if you'd like a different name, let me know.

### CODE REVIEW

**Comment by nikhilk** [comment]
I think you could probably just call it BindingContext to go along with the existing generic BindingContext implementation. Should this be implemented as overloads... i.e. is there a scenario where this is not needed? If not, as in a binding context is always needed, then there should be overloads for accepting this as well as the generic type.

Secondly, I fixed up the previous pull request ... could you look back at the changes I did subsequent to merging it for making sure the changes in this one also adhere to exiting patterns (headers, line spacing, bracing style).

**Comment by michaelaird** [comment]
Sorry. I will review the style. 

I tried calling it BindingContext but I ran into compilation problems. The Knockout "reference" project compiled just fine but when i tried to compile my own project referencing the updated knockout assembly, it threw a bunch of "make sure you aren't using unsupported features" errors. Do I need to add special attributes or something?

**Comment by michaelaird** [comment]
Also, the reason i introduced this other type is because inside a BindingHandler, you don't necessarily know the generic types for the BindingContext. there could be a bunch of different types of viewmodels, etc being bound to a handler. so, i don't think an overload that takes the generic type makes sense.

**Comment by nikhilk** [comment]
OK, but we'd still need the overload that takes an object, so one can pass in an instance of a generic BindingContext.

On that note, one other thought... couldn't you just use BindingContext&lt;object, object, object&gt; ... while I agree, its not very pleasant, but it avoids the need to add another type.

**Comment by michaelaird** [comment]
Agreed, i've removed the new type and changed to use BindingContext < object, object, object >.

**Comment by nikhilk** [comment]
I think the signature shouldn't use BindingContext ... but rather just vanilla object. A different generic instantiation that doesn't use object for all three generic type arguments would not be usable with the current signature.

**Comment by michaelaird** [comment]
ok. sure. i thought it might be nice to have it strong-er typed but i'm happy to just make it "object" and people can cast it if they need to access it.

**Comment by nikhilk** [comment]
Was going to merge this, but thought about double checking the docs first ... doesn't seem to match. As per http://knockoutjs.com/documentation/custom-bindings.html which has this snippet:

```
ko.bindingHandlers.yourBindingName = {
    init: function(element, valueAccessor, allBindingsAccessor, viewModel) {
    },
    update: function(element, valueAccessor, allBindingsAccessor, viewModel) {
    }
};
```

The change doesn't seem right - its adding a fifth parameter context, when there isn't one. The old signature looks like it matches what is in the Knockout docs, and an instance of BindingContext is already passed in into these methods as the viewModel parameter.

If you (and others who are using the knockout APIs) can either confirm this change and whether it is needed would be good. If its confirmed to be needed, I'll simply make the change to avoid having to save history of individual commits on the this one with back-and-forth on new type/removal of new type etc.

**Comment by michaelaird** [comment]
I believe the BindingContext was added in this commit (https://github.com/SteveSanderson/knockout/commit/3fe0da755289e61815912f9804a5645016a5fc0b) over a year ago. I'm not sure why the docs haven't been updated.

**Comment by dealproc** [comment]
Sorry to highjack this one @michaelaird, but it seems pertinent.  In order to add a custom binding handler via Script# (e.g. http://www.knockmeout.net/2011/05/dragging-dropping-and-sorting-with.html), would we do:

``` C#
Knockout.BindingHandlers.Add("SortableList", typeof(SortableList));
```

then?

**Comment by nikhilk** [comment]
I think you'd do the following:

```
static SortableList() {
    Knockout.BindingHandlers["SortableList"] = new SortableList();
}
```

**Comment by michaelaird** [comment]
Yup. That's what I do.

**Comment by dealproc** [comment]
Ah, gotcha.  Is his sortable in code somewhere, or do I have to script it quick?  So far, I don't recall seeing it.

**Comment by michaelaird** [comment]
For any binding handlers that already exist in JS, like knockout-validation
or knockout-sortable, i just reference them in my html views. for binding
handlers that i've written myself in Script#, i register them using the
sytnax @nikhilk gave above.

**Pull request closed without merging**
