### PR TITLE
Fixed line endings

### PR DESCRIPTION
**Pull request by cascadian**
...d line endings.

I was having trouble with some of the line endings so I contacted GitHub
support. I'm following Phil Haack's suggestion in committing these
changes. Including his email for additional context:

From: Phil Haack (GitHub Staff)
Subject: commit changes entire file

Hi Paul,

You're doing everything right. This is a tricky situation because you're
dealing with someone else's repository.
The problem is that his repository already has messed up line endings.
My recommendation to you is to make
the big commit with all the fixed up line endings and
.gitattribute/.gitignore file and send a pull request.

Mention that @haacked suggests the changes in the pull request (Nikhil
knows me) message and maybe even
copy this email. Fixing the .gitattribute file for his repo is a good
idea and he may appreciate the pull request.

Phil

### CODE REVIEW

**Comment by nikhilk** [comment]
Paul, thanks for looking into this.

Most of the files here seem like they've been touched by multiple folks over time, so that probably explains the mixed line endings... would be good to fix ... and ideally, even figure out how to prevent getting into this state, given everyone has their own setting (or is there a way to create a per-repository crlf setting?). FWIW, my autocrlf setting is set to true on my machines.

How did you detect all files that have mixed line endings, and fix them? Is there some automated way?

That said, looking at the diff, I am unsure why I see certain things:
- Various entries in .gitignore and .gitattributes file. For example, an entry for .vbproj in gitattributes, and all sorts of stuff that will never show up in the repo to be ignored.
- jQuery stuff ... clearly not related to line endings. I also looked at this change and not completely sure about it. IIRC, the compiler doesn't support the level of generics you're using in the added overloads. Did you successfully use the resulting jQuery assembly, and the specific overloads you added successfully in another script# project?

I'd love to see a change focused on fixing line endings as a separate change.

**Comment by strygo** [comment]
I had this problem with one of my repos and all you should need is a single line in the .gitattributes file:

[asterisk] text=auto

This will ensure consistent behavior for everyone working on the repo.

Separately, GitHub for Windows has an option to correct the line endings for an entire repo.

**Comment by haacked** [comment]
> even figure out how to prevent getting into this state, given everyone 
> has their own setting (or is there a way to create a per-repository crlf setting?).

@nikhilk That's exactly what a `.gitattributes` file does. The one that @cascadian is trying to commit is the one recommended for Windows developers by GitHub for Windows. It probably has more than what you specifically need, but there's no harm in having the extra entries.

> How did you detect all files that have mixed line endings, and fix them? Is there some automated way?

As @strygo points out, GHfW does that. When you set this, it'll create a commit that fixes up everything in your repo.

> Various entries in .gitignore and .gitattributes file.

You can ignore the changes in the `.gitignore` file. Those are also recommended by GitHub for Windows, but if they don't do what you need, ignore them. Entries in .gitattributes do not control whether files are ignored or not by git.

@strygo For certain file types, `merge=union` produces a better result. It doesn't leave conflict markers in the file (which would cause files such as .csproj) to not load. Of course, it's important to verify merges in all cases.

Phil

**Comment by cascadian** [comment]
Hi Nikhil, I did successfully use the Pipe() overload in another Script# 
project. You would know the compiler's limitations a lot better than me 
though. I could commit the sample Script# project in a new repository so you 
can take a look if you want.

My intention was to have separate pull requests for the 2 commits, but 
somehow GitHub detected the existing pull request and appended the jQuery 
commit to it.

Paul

-----Original Message-----

**Comment by nikhilk** [comment]
I did look at the description with the jQuery commit, and if that works, that should be fine.
I'll look into pulling specific commits from your repo individually.

**Comment by nikhilk** [comment]
I tried to pull your specific commit for the jQuery update by pulling from your repository (using git cherry-pick based on what I read around) and while I think I succeeded in doing so, it seems to show up as my commit rather than a pull from your repo, which is what I expected/hoped. Sorry about that...

I believe when you create a pull request, you can customize the commit range based on what I read as well.

**Comment by nikhilk** [comment]
Incorporated the .gitattributes change.

**Pull request closed without merging**
