### PR TITLE
set jQueryPosition wasn't possible

### PR DESCRIPTION
**Pull request by andekande**
now you can use [jQueryObject].Offset(new Dictionary("top", topvalue,
"left", leftvalue));

### CODE REVIEW

**Comment by nikhilk** [comment]
I don't think that would be the desired code you want to enable. I think the following is more desirable:

```
someObj.Offset(new jQueryPosition("top", topValue, "left", leftValue)
```

as it is in line with what we want in the future:

```
someObj.Offset(new jQueryPosition() { Top = topValue, Left = leftValue });
```

So what we should do is:
1. Add a parameter-less public ctor, and another overload that takes in params object[] nameValuePairs.
2. Make Top/Left settable properties
3. Apply a ScriptName("object") attribute on the class.

**Comment by andekande** [comment]
Hi, I took your approach before pushing, but there is a side effect in declaring ScriptName("object") with that JS wasn't able to run. It messes up the whole Application code, so no entry point is found.
In fact in current code this implicit conversion was already there - just the wrong way.

**Comment by nikhilk** [comment]
I tried and it worked fine... see my recent commits for the changes.

The existing conversion was to allow casting jQueryPosition to a dictionary to be able to index into it, rather than to allow using a dictionary wherever jQueryPosition was accepted (which wouldn't be typical).

**Comment by andekande** [comment]
works, thanks a lot

**Pull request closed without merging**
