### PR TITLE
Additions to Knockout Mapping bindings to support arrays

### PR DESCRIPTION
**Pull request by stevehobbsdev**

### CODE REVIEW

**Comment by aschoenebeck** [comment]
Thanks a lot. I need array create options to simplify ajax loading into ObservableArrays via Knockout.Mapping. Please merge and release soon!

**Comment by nikhilk** [comment]
Looks like pull requests accumulate all previous and unrelated changes, which isn't allowing me to merge this. I'll incorporate the changes into the cc branch.

**Comment by stevehobbsdev** [comment]
Hmm I think I've messed up this a little bit. I think what's happened is, I put in the change to jQueryAjaxOptions in my master fork. I then branched it to put the other changes in for each library, but obviously they all have the jQueryAjaxOptions change as well.. 

Sorry about that - is there anything I can do from my end to help the situation?

**Comment by nikhilk** [comment]
No problem. The changes are limited enough that they're easier to deal with manually than try to do the right thing which is pull just the right commits. I'll just take care of them.

**Comment by nikhilk** [comment]
Added your updates... hopefully it doesn't result in too many merge conflicts on your end.

**Pull request closed without merging**
