### PR TITLE
Added support for HTML5 File Access API

### PR DESCRIPTION
**Pull request by theoutlander**
Added support for HTML5 File Access API by creating stubs for Blob, BlobPropertyBag, File, FileList, FileReader, DOMError, ProgressEvent. Also exposed the classes in the Window class.

I've implemented the functionality by following what's listed under: http://www.w3.org/TR/FileAPI/, MDN and by looking at what's exposed in javascript when I manually instantiated these objects.

I've followed the coding guidelines and tested this locally. Since this is my first major checkin, let me know if there's anything that needs to be changed or clarified. Thanks!

### CODE REVIEW

**Comment by nikhilk** [comment]
Very cool... thanks.

One suggestion/question - could this go under System.Html.Data.Files? So its closer to the SQL and IndexedDB related APIs?

From the samples, I noticed HTML elements (maybe specific ones like a file input element) have a Files property. Is that covered in the APIs added here?

I think most of the coding guidelines have been followed. Thanks. One thing I'd appreciate is the ordering of members per the order noted in the wiki.

Finally, I am seeing a message that this pull request can't be automatically merged. It helps if it can be. I suspect you'll need to do a git pull on your end to pick up the latest changes, and then submit a new pull request.

**Comment by theoutlander** [comment]
I meant to ask about the namespace prior to implementing. System.Html.Data.Files seems like the right location. I've moved the files and renamed the namespace.

Good catch on the Files property. Totally missed that. Since the files property is only applicable when type="file", would the right way to do this be to create a derived class FileInputElement (from InputElement) and create a Files property? The user would still have to specify the input type....the way to get around that might be to create a generated script instead of ScriptImport, but I'm not sure if that'll work right. What do you suggest?

I've ordered the members as per the wiki. I found a mis-match in window that I've corrected. Let me know if there's something else.

I didn't realize that my fork was from several months ago. I've merged the changes.

I can send a pull request for the Input Element changes once we decide what's the right thing to do there.

**Comment by nikhilk** [comment]
Yes, lets create a FileInputElement at this point...

**Comment by theoutlander** [comment]
I've made the suggested changes, reordered methods and created the FileInputElement class. This should be ready to pull now.

**Comment by nikhilk** [comment]
Few more things I noticed (should have looked in more detail last night). So, I am happy to make the changes if you like upon merging. Just let me know...
- Can we rename DOMError to FileError. The former sounds too generic.
- Same goes with ProgressEvent. Probably should be FileProgressEvent. Is there a reason it doesn't derive from Event which already has members for Target, SrcElement, etc. etc.
- Nested class BlobPropertyBag should be top-level class. Also should have right metadata attributes on it (ScriptImport, ScriptObject). Or alternatively just don't have the type and use object options in the 3rd Blob ctor (which would let someone pass in an object literal constructed using a Dictionary ctor ... at loss of some strong typing. Depends on how often that ctor is used vs. other two).
- FileList - does it actually have an Item method or does an indexer also work? I wouldn't be surprised if the indexer works at runtime, and it would be better.
- Bunch of ushorts for things like ready state on FileReader could probably just be an int. Or better yet an enum. Those consts should be replaced by a FileReadyState enum.
- FileInputElement should be sealed and have a private ctor. It should not need a ScriptName metadata attribute.
- Small nit - can you add a new line at the end of every file. That will keep from github source views from adding a line indicating "No newline at end of file" for every file.
- I actually suggested "Files" to be the subnamespace. I think that looks a bit nicer...

**Comment by theoutlander** [comment]
Thanks for the detailed feedback. I contemplated about some of these issues. I struggled with some decisions mainly because of inconsistencies in the spec, MDN and looking at the object structure of actual instances. Mostly, this being my first time contributing to the repo. I'll definitely go fix them tonight.
- Specifically, I used DOMError and ProgressEvent to be consistent with the W3C API spec. Making it specific to File is also a good idea. I left it as a nested class so it was restricted to File API.
- ProgressEvent should derive from Event. I think that's the right way to go. There are several properties that are missing in it which I'll need to look into as the spec doesn't define them, but MDN had them or I found them in the instantiated object. I think ProgressEvent is slightly incomplete and needs to be finished.
- You are right about BlobPropertyBag - I just couldn't decide which way to go. Decided on the typed object so that it makes it clear what is expected, but we need to keep the structure updated every time. I'm ok with a simple  dictionary there for now. I haven't really had to use it for any of my use cases.
- So I tried to do both item and the indexer and the compiler complained that they're the same thing. So I went with item function for some odd reason as I had to pick one....I don't like it myself and I think indexer is a better alternative, so I'll change it to that.
- UShort to Int based enum is a good idea. We also don't need the CLSCompliant attributes then.
- FileInputElement - agree with the sealed and pvt ctor, but don't understand why ScriptName shouldn't be there... the usage generally would be something like document.getElementById('elemID') as FileInputElement .... if I don't specify InputElement, how would js interpret fileInputElement in the generated JS?
- Yeah the newline was bugging me too...the guidelines didn't state anything, so I did what I normally do.
- Files -  You're right. I ended up moving the folder in the solution and forgot to rename it...resharper ended up syncing the names.

**Comment by nikhilk** [comment]
Reply to your FileInputElement followup question:

The ScriptName only comes up when you refer to the type name in script - which is at construction time (doesn't apply here since elements are created using createElement factory method) or when doing a type check. There is a little gotcha in that stuff like is/as don't work with intrinsic types such as DOM types, so it wouldn't apply there either (even though it ideally could/would).

Overall, thanks for the contrib, plus following up. You've seen first hand some of the thought that needs to go into creating these import libraries (rationalizing multiple sources of info, seeing what works best for c#, and finding what to include/leave out etc.) ... many ask me why there is no auto-importer, and this is the reason. :)

**Comment by theoutlander** [comment]
Thanks for your patience while I come up to speed with the commit guidelines. Hopefully, this one is closer to the standards.

**Comment by nikhilk** [comment]
Thanks for contributing.

I did make a few changes including some slight naming changes and making FileError and FileProgressEvent non-constructable as well as added of FileReaderSync which I noticed as I was trying to get a sense of the file APIs from the spec.

**Comment by theoutlander** [comment]
Cool, thanks for fixing those. I went through the changes and noticed I made several silly mistakes.

I ignored FileReaderSync since I couldn't instantiate that object in the console and assumed it didn't exist yet. I suppose it's only available in a WebWorker?

Cleaning up the Node-Neo4J API now.

**Comment by theoutlander** [comment]
Btw, can you share code formatting settings for ReSharper, VS or other utilities that you use? That way contributors don't have to spend too much time on formatting.

**Comment by nikhilk** [comment]
Unfortunately I don't have any specific resharper or other tool settings (which, yes, makes things hard to guide/validate). Don't know how flexible resharper is to capture the various rules.

The only settings I have are around what VS exposes for spacing and bracing style. On the latter group, I changed default settings to keep open brace on the same line.

**Pull request merged**
